name: job-scheduler
version: 0.3.0.0
synopsis: Simple in-memory job scheduling
description: See README
maintainer: Jesse Kempf
github: binarysunrise-io/job-scheduler

ghc-options: -Wall -O2

dependencies:
  - QuickCheck
  - aeson
  - amazonka
  - amazonka-dynamodb
  - base >= 4.7 && < 5
  - bytestring
  - cron
  - pqueue
  - text
  - time
  - transformers
  - containers
  - mtl
  - microlens
  - microlens-platform
  - monad-logger
  - exceptions
  - prometheus-client >= 1.0.0 && < 2
  - stm
  - unliftio-core

library:
  source-dirs: src
  exposed-modules:
    - Control.Scheduler
    - Control.Scheduler.Chronometer
    - Control.Scheduler.Class
    - Control.Scheduler.Runner.SingleThreaded
    - Control.Scheduler.Schedule
    - Control.Scheduler.Time
    - Control.Scheduler.Type
tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
    dependencies:
      - job-scheduler
      - hspec >=2.0.0
      - temporary
